package com.example.comida.dummy

import com.example.comida.models.FoodItem
import com.example.comida.models.burgerFoodAddOns
import kotlin.random.Random


val burgersCategory = listOf<FoodItem>(
    FoodItem(
        categoryID = "Burger",
        title = "50/50 burger",
        description = "Half ground bacon, half ground beef burger patty developed by Scott Slater for Slater's 50/50 restaurant. Another variety is half kangaroo meat and half bacon.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://assets3.thrillist.com/v1/image/770942/1200x600/scale;;webp=auto;jpeg_quality=85.jpg"
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Afghani burger",
        description = "Also known as the Kabuli burger or the Ayatollah Burger, an Afghan fast food wrap consisting of a piece of Afghan bread rolled around french fries, along with chutney and other condiments, vegetables, and often sausages or other meat.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://www.sandwichtribunal.com/wp-content/uploads/2021/04/IMG_5452.jpg"
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Angus burger",
        description = "A hamburger made using beef from Angus cattle. The name Angus burger is used by several fast-food hamburger chains for one or more premium burgers; however, it does not belong to any single company. Pre-made frozen Angus burgers are increasingly available from retailers.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfC9I9r7ZboRmLoyEbVn7aPG6zCZ8m6-FC3A&s",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Kiwiburger",
        description = "Popular regional hamburger ingredients in Australia and New Zealand include canned beetroot, pineapple and a fried egg. Pictured is a burger with slices of canned beetroot within it.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://cdn.sanity.io/images/p6oh2x2n/production/881deeee2f8b8d2467d639fa5d467403ccfcb639-1920x1080.jpg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Bacon cheeseburger",
        description = "Hamburger with bacon and cheese is a bacon cheeseburger, which became an official menu item at an A&W Restaurant owned by Dale Mulder in Lansing, Michigan, in 1963. Hamburgers with bacon but no cheese may be referred to as bacon burgers.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://www.meatloafandmelodrama.com/wp-content/uploads/2017/05/jalapeno-bacon-cheeseburger.jpg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Banquet burger",
        description = "Cookbook author Kathleen Sloan-McIntosh credits Francis Deck as the inventor of this burger, stating its original name was the Forest Hill burger. Similar to a bacon cheeseburger, this burger is often served open-faced, with the hamburger patty, cheese, and bacon on a flat bottom bun next to the top rounded bun containing the lettuce, tomato, and onion slices. The ground beef contains black pepper, Worcestershire sauce, and grated onion. Condiments used are mayonnaise, mustard, ketchup, and dill pickles.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://banquetburger.com/wp-content/uploads/2023/10/Untitled-design-41-640x640.png",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Bøfsandwich",
        description = "Classic Danish take on a hamburger. It contains the hamburger elements of a cooked ground beef patty placed inside a sliced bread roll. Bøfsandwiches are traditionally sold from hotdog stands and other fast food establishments, but some traditional Danish restaurants have started serving gourmet versions.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://eatsy.bold-themes.com/burger/wp-content/uploads/sites/2/2018/09/product_03.jpg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Butter burger",
        description = "In the Upper Midwest, particularly Wisconsin, burgers are often made with a buttered bun, butter as one of the ingredients of the patty or with a pat of butter on top of the burger patty.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://dinnerthendessert.com/wp-content/uploads/2025/03/butter-burger-42-cropped.jpg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Buffalo burger",
        description = "Prepared with meat from the American bison, buffalo burgers have less cholesterol, less fat, and fewer calories than beef hamburgers and chicken hamburgers. The American Heart Association recommended buffalo burgers in 1997 as more heart-healthy than chicken or beef.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiqpsVo9kePgC6SoP6VS5pbI8GKCJr2EXCQA&s",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "California burger",
        description = "In the Western U.S., a California burger most often consists of a normal cheeseburger, with the addition of bacon and either guacamole or avocado.[10] In the Eastern U.S., a California burger is traditionally a burger with lettuce, tomato, and raw onion.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://www.rachelcooks.com/wp-content/uploads/2024/07/California-Burger-WEB-24-square.jpg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Cheeseburger",
        description = "Hamburger accompanied with melted cheese. The term itself is a portmanteau of the words cheese and hamburger. The cheese is usually sliced, then added a short time before the hamburger finishes cooking to allow it to melt. In fast food restaurants, the cheese that is added to a cheeseburger is typically American cheese, but there are many other variations. Mozzarella, blue cheese, Swiss cheese, pepper jack, and especially cheddar are popular choices.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://leitesculinaria.com/wp-content/uploads/2020/02/classic-cheeseburger-1200.jpg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Chili burger",
        description = "Consists of a hamburger, with the patty topped with chili con carne",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://dyvn6jpt1f0d3.cloudfront.net/wp-content/uploads/2020/10/12151623/IMG_1332-scaled-e1611171206740.jpg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Chimichurris",
        description = "Ground beef, chicken, or pork leg served on pan de agua and garnished with cabbage and salsa rosa.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://leitesculinaria.com/wp-content/uploads/2020/02/classic-cheeseburger-1200.jpg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Chori burger",
        description = "A Filipino hamburger characteristically made with chorizo (longganisa) patties, banana ketchup, mayonnaise, and atchara, in addition to tomatoes and lettuce. It was first popularized by Merly's BBQ, a street food stall in the island of Boracay in the Philippines.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://static01.nyt.com/images/2014/04/04/multimedia/fc-jeepney/fc-jeepney-superJumbo-v2.jpg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Green chile burger",
        description = "Burger topped with roasted New Mexico green chiles. Many places around New Mexico serve variations of this burger.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUJvW3D16FbSRm4A-zislAhEt3e4DW_4q9LQ&s",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Guber burger",
        description = "Burger topped with peanut butter",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://www.thecookierookie.com/wp-content/uploads/2023/10/peanut-butter-burgers-recipe.jpg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Hamdog",
        description = "Australian invention that consists of a special combination hamburger and hotdog bun. A meat patty is split in half and has a sausage run through the middle. It is then topped just as a conventional burger.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThr-VDJLQKNsfmwK6aGZn1IxNVH5oPn-trT7ooN2bhsRwlBK_ZmxA9lBBy3XiJd4x1FCk&usqp=CAU",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Islak Burger",
        description = "A Turkish street food composed of a hamburger soaked in tomato sauce, served with a mystery sauce. Popular around Taksim Square in Turkey.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://static.ticimax.cloud/cdn-cgi/image/width=540,quality=99/9247/uploads/blog/islak-hamburger-nedir-ve-nasil-yapilir-e3ec.jpeg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Jucy Lucy",
        description = "A cheeseburger that has the cheese inside the meat patty rather than on top. A piece of cheese is surrounded by raw meat and cooked until it melts, resulting in a molten core of cheese within the patty.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFF00OhYZG3k-Dot9ELY0TwBgFrGuAwro7pg&s",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Kimchi burger",
        description = "A hamburger that includes kimchi in its preparation",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://www.seriouseats.com/thmb/TI1XJh4710434bN8InouOVLzBfM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2017__06__20170617-bulgogi-burger-matt-clifton-1-b9769887cb1e4a4a8d9e9922bbabcace.jpg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Louis' Lunch",
        description = "A hamburger made with ground steak made from a blend of five cuts of beef, vertically flame broiled, then served on two square pieces of toasted white bread.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://s.hdnux.com/photos/01/37/43/06/25047446/5/1440x0.jpg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Luther Burger",
        description = "Hamburger or cheeseburger prepared with one or more glazed doughnuts in place of the bun",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://images.slurrp.com/prod/recipe_images/the-spruce-eats-set-2/luther-burger-doughnut-bacon-cheeseburger-4018810-1620404439_5UFKDCNJNKY03WSYYAHK.webp",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Office Burger",
        description = "A burger of dry-aged beef, blue cheese and Gruyère cheese, caramelized onions, applewood bacon compote and served on a toasted oblong shaped French baguette. Father's Office has a no-modification policy for the Office Burger that will not allow substitutions or add-ons of any kind such as ketchup.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://popmenucloud.com/cdn-cgi/image/width=1200,height=630,format=auto,fit=cover/mixkarbu/54c87959-05ce-4a97-82c8-ded55f3c0bbf.webp",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Oklahoma onion burger",
        description = "A burger with a large amount of thinly sliced onions piled on top of the ground beef before smashing the patty into the grill to embed the onions in the beef. It was conceived of during The Great Depression in Western Oklahoma as a way for local diners to stretch ground beef.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://www.seriouseats.com/thmb/naUL3asafVlR1YnTi2uCpgPAdQM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20210607-OKONIONBURGERS-JANJIGIAN-seriouseats-1ff54150234c421fa78a71da44ef1f6d.jpg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Olive burger",
        description = "A burger topped with olive sauce, a mixture of chopped green olives and mayonnaise. Most likely originating at Weston's Kewpee Sandwich Shop in the 1920s, olive burgers are a popular local fast food burger in the Lansing metropolitan area.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://bushwickgrillclub.com/wp-content/uploads/2023/11/OliveBurgerCrop_edited-960x1139.jpeg",
    ),
    FoodItem(
        categoryID = "Burger",
        title = "Pastrami burger",
        description = "A burger with cheese and thin-sliced pastrami on top, commonly served at Greek burger restaurants in Utah.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = burgerFoodAddOns,
        image = "https://jamiecooksitup.net/wp-content/uploads/2016/08/Pastrami-Burger.jpg",
    ),
)