package com.example.comida.dummy

import com.example.comida.models.FoodItem
import com.example.comida.models.donatsFoodAddOns
import kotlin.random.Random


val donutsCategory = listOf<FoodItem>(
    FoodItem(
        categoryID = "Donuts",
        title = "Cake Donuts",
        description = "Cake donuts are a type of doughnut made from a dense, cake-like batter that uses chemical leaveners like baking powder and baking soda for lift, instead of yeast, which is used in yeast donuts. They have a tender, moist, and often crumbly interior with a slightly chewy, crisp exterior, a texture distinct from the lighter, airier crumb of yeast-risen donuts. Cake donuts are quick to make, can be flavored in many ways, and can be either fried or baked.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://sugargeekshow.com/wp-content/uploads/2020/09/cake_donut_recipe_featured2.jpg",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Cruller",
        description = "A cruller is a deep-fried pastry that can be either a dense, cake-like doughnut or a light, airy, and ridged doughnut made from choux pastry, like a French cruller. Unlike many doughnuts made with yeast or chemical leavening, French crullers use choux pastry (the same dough as for eclairs). This dough is piped, fried, and typically glazed, creating a crispy exterior and a soft, airy interior. The name \"cruller\" itself may come from the Dutch word \"krullen,\" meaning \"to curl,\" referencing their often twisted or ridged shape.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://assets.epicurious.com/photos/54b026ee766062b20344655e/6:4/w_1010,h_673,c_limit/51157200_french-crullers_1x1.jpg",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Jelly Donut",
        description = "A jelly donut, also known as a jam donut or Berliner, is a type of raised doughnut that is filled with fruit jelly, jam, or preserves. These sweet treats are often fried, rolled in sugar, and are popular in many cultures, especially for holidays like Hanukkah (where they are called sufganiyot).",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRSHybwf1d5KjQcicHAYx2jrYUKioGUSviBQ&s",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Old Fashioned Donut",
        description = "The old-fashioned doughnut is a term used for a variety of cake doughnut prepared in the shape of a ring with a cracked surface and tapered edges.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://www.littlesweetbaker.com/wp-content/uploads/2020/04/old-fashioned-donuts-1.jpg",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Glazed donut",
        description = "Glazed Doughnuts are a type of sweet food that are coated with powdered sugar glaze. They are a classic and popular type of sweet yeast dough.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXHWen6NdXvsU474nwr3DDghL7HfF1iIk2MLmclu-j9IPDZzlGilcXkEiSshy8VgRZEGQ&usqp=CAU"
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Boston Cream",
        description = "Boston cream donuts are always topped with chocolate and filled with pastry cream, just like a Boston cream pie or my Boston cream cupcakes.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://bakerbynature.com/wp-content/uploads/2021/08/Boston-Cream-Donuts-1-1-of-1.jpg",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Chocolate Donut",
        description = "A chocolate donut is a sweet, typically ring-shaped pastry that incorporates chocolate into the batter, glaze, or filling, offering a moist, cakey, or fried texture and a distinct chocolate flavor. Common variations include baked chocolate donuts with rich chocolate glaze and toppings, as well as fried versions that can be covered in powdered sugar or chocolate icing.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaMASdXAnOHCfMIuy59kKwX-bcbegb87GcfA&s",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Donut Holes",
        description = "Donut holes are small, ball-shaped pastries made from donut dough, sometimes as a way to use up the dough cut out from the center of traditional ring donuts. They can be plain or coated in toppings like glaze or powdered sugar and are popular as a snack. Popular brand names for donut holes include Tim Hortons' \"Timbits\" and Dunkin's \"Munchkins\".",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_4:3/k%2FPhoto%2FRecipe%20Ramp%20Up%2F2021-10-Donut-Holes%2Fkitchnoctkitchnoct3958-1",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Long John",
        description = "A Long John is a long, bar-shaped doughnut made from a yeast-risen dough that is deep-fried. It's characterized by its rectangular shape, as opposed to the traditional round doughnut. While the term \"Long John\" is regional, commonly used in the Midwest and parts of Canada, these doughnuts can also be called \"bars,\" \"maple bars,\" or \"chocolate bars\" on the West Coast, or sometimes \"éclairs\" in other areas, though éclairs use a different dough. Long Johns can be left unfilled or filled with custard, cream, or jam, and are typically topped with a sweet glaze or frosting like chocolate or maple. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3uXKceQJTlgD-AilQk_uYggdC3fzg1hn7DA&s",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Yeast Donuts",
        description = "Yeast donuts, also known as raised donuts, are a type of fried pastry made from a light, enriched dough leavened with yeast, giving them a characteristic light, airy, and slightly chewy texture with a honeycomb interior. The yeast allows the dough to rise, resulting in a puffy donut that differs from the denser, cake-like texture of chemically-leavened cake donuts.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4U3sV3jXbmu97WNZuOiPnsEqs8d-REZgK9Q&s",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Blueberry Donut",
        description = "Soft and fluffy cake donut base studded with blueberries and topped with a sweet and tangy lemon blueberry glaze. If you're looking for a cake donut recipe this is the one! Tips on the Donut. Tips on the glaze.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://cardamomandtea.com/wp-content/uploads/2021/06/IMG_2059-min.jpg",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Cronut",
        description = "A Cronut is a specific brand name and type of pastry, trademarked by Dominique Ansel Bakery, that is a hybrid of a croissant and a doughnut. It features a flaky, buttery, croissant-like dough shaped like a doughnut, which is then deep-fried until crispy, filled with cream, and glazed. Because the name \"Cronut\" is trademarked, other bakeries create similar pastries under different names, such as \"crodough\" or \"doughtssant\". ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://whiskfullyso.com/wp-content/uploads/2021/02/Strawberry-Vanilla-Cronut-10.jpg",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Apple Fritter",
        description = "An apple fritter is a deep-fried pastry that consists of diced or sliced apples folded into a sweet batter, then fried until golden brown. Often flavored with cinnamon and coated in a sugar or glaze, apple fritters are similar to a donut and are a popular sweet treat, commonly enjoyed for breakfast or dessert, especially in the fall. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://www.smalltownwoman.com/wp-content/uploads/2019/04/Apple-Fritters-DSC_0145-4.jpg",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Beignet",
        description = "Beignet is a type of deep-fried pastry of French origin. It is commonly made from pâte à choux, but can also be made using rice flour or yeast-leavened batters. Beignets can be served in a variety of preparations, the most common being dusted with confectioner’s sugar. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://tatyanaseverydayfood.com/wp-content/uploads/2022/10/Sea-Salt-Caramel-Beignets-Recipe-2.jpg",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Chocolate Frosted Donut",
        description = "Homemade chocolate frosted donuts are baked, not fried, and topped with a thick chocolate glaze. This easy recipe for moist and buttery donuts will quickly become a favorite breakfast treat. Cover them completely in sprinkles and you'll find yourself eating more than just one!",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://www.barbarabakes.com/wp-content/uploads/2022/11/chocolate-glazed-donuts-recipe-35-of-38-500x500.jpg",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Cider Doughnut",
        description = "A cider doughnut, or apple cider doughnut, is an American cake doughnut flavored with apple cider and spices like cinnamon and nutmeg, often boiled down into a concentrate for a deeper apple taste. A fall tradition, especially in the northeastern United States, these doughnuts are deep-fried until golden brown and typically coated in a mixture of cinnamon and sugar. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThkpjj5DG9VPDUqFK4RgtuHzq_maU85Y0ckw&s",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Filled Donuts",
        description = "Made from scratch, these easy Homemade Filled Donuts are made with an old-fashioned enriched dough that's lightly sweet, fluffy, and pillowy. With three choices of filling—cheesecake, jelly, Nutella, oh my! —there's something for everyone.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxoU7dgUlj2-WWVIKPPg8fxS77d2Lj3CAKmg&s",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Mochi Donut",
        description = "Mochi donuts, also known as poi mochi, are a fusion pastry crossing traditional American-style doughnuts and Japanese mochi. The mochi donuts' \"hybrid batter makes for a doughnut that is fluffy and moist, with a satisfying chew\". An early iteration can be traced back to Hawaii in the early 1990s.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://thebigmansworld.com/wp-content/uploads/2022/07/mochi-donut-recipe.jpg",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Churro",
        description = "A churro is a type of fried dough from Spanish and Portuguese cuisine, made with choux pastry dough piped into hot oil with a piping bag and large closed star tip or similar shape.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://mikebakesnyc.com/wp-content/uploads/2018/05/Photo-Aug-05-6-47-01-PM-683x1024.jpg",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Sour Cream Donut",
        description = "A sour cream doughnut is a type of doughnut that incorporates sour cream into its batter. This type of doughnut is often dipped in a vanilla flavored glaze after frying and usually has no filling.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT44JGaH0kSszybA8Yb2VjL3vN0rl9kUcqF2g&s",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Zeppole",
        description = "Zeppole are Italian pastries consisting of a deep-fried dough ball of varying size but typically about 4 inches in diameter. These fritters are usually topped with powdered sugar, and may be filled with custard, jelly, cannoli-style pastry cream or a butter-and-honey mixture.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://gluttodigest.com/wp-content/uploads/2020/12/zeppole-italian-donut-holes-720x540.jpg",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Malasada",
        description = "Malassada is a Portuguese fried pastry from the Azores. It is a type of doughnut, made of flattened rounds of yeasted dough, coated with sugar and cinnamon or accompanied with molasses. The name malassada is often used interchangeably with filhós.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://preppykitchen.com/wp-content/uploads/2022/03/Zeppole-Blog2.jpg",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Strawberry Donut",
        description = "A strawberry donut is a donut that has been infused with or flavored by strawberries, most commonly by being dipped in a strawberry-flavored glaze, filled with a strawberry cream or jam, or having pieces of fresh strawberry in the dough. They can be made from a fried yeast dough or a baked cake batter and are often decorated with sprinkles or fresh strawberries. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpNEvm_a3sxD1Wlf81d17uxd8QUeR-IoPU9w&s",
    ),
    FoodItem(
        categoryID = "Donuts",
        title = "Sugar Donut",
        description = "This simple homemade donut dough is made with flour, milk, egg yolks, yeast, and sugar, then the donuts are fried and dredged in sugar. This recipe is easy to make and produces a very indulgent little treat! Make it once and you'll never use a different recipe for donuts.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = donatsFoodAddOns,
        image = "https://bakeitwithlove.com/wp-content/uploads/2022/09/lemon-sugar-baked-donuts-sq-500x500.jpg",
    ),
)