package com.example.comida.dummy

import com.example.comida.models.FoodItem
import com.example.comida.models.hotdogFoodAddOns
import kotlin.random.Random


val hotDogCategory = listOf<FoodItem>(
    FoodItem(
        categoryID = "HotDog",
        title = "New York Hot Dog",
        description = "Since hot dogs were first introduced in New York, we’d be remiss if our tour didn’t start in the Big Apple! And a trip to the bustling city isn’t complete without a street-side snack from a food cart—home of this simple hot dog packed with flavor. Almost similar to “Chicago-style” (which we’ll get to in a bit) the New York-style hot dog starts with a boiled beef or pork dog.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://colemannatural.com/wp-content/uploads/2023/08/Two-new-york-hot-dogs-topped-with-ketchup-and-mustard-920.jpg"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Chicago Style Hot Dog",
        description = "So what is a Chicago-style hot dog exactly? It all starts with a steamed dog and fluffy poppy seed bun. This provides the foundation for a variety of toppings, such as mustard, chopped white onion, pickle relish, pickled sports peppers, and a dill pickle…holy pickle. But it doesn’t stop there. Chicagoans add freshly sliced tomatoes and a dash of celery salt that heightens the flavor profile.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://colemannatural.com/wp-content/uploads/2023/08/Chicago-style-hot-dog-on-a-table-920.jpg"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Coney Hot Dog",
        description = "So what makes these so unique from the rest? It’s the chunky chili “Coney” sauce, made with a ground beef or beef and pork mixture, along with various seasonings such as chili powder, onion, garlic, and sometimes a hint of cinnamon. On top of this irresistible mixture, you might find a layer of onions and mustard too.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://colemannatural.com/wp-content/uploads/2023/08/Three-Coney-Dogs-on-a-wooden-cutting-board-920.jpg"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Cincinnati Chili Hot Dog",
        description = "Typically made with fresh ground beef, water, or broth, and a blend of spices that can include cinnamon, allspice, cloves, and cocoa powder, this chili warms the soul, especially on a cold day. And topped on a hot dog? Well, it’s pure heaven. Plus, traditionally, the Cincinnati chili dog is loaded with shredded cheddar cheese, which makes this hot dog another messy, yet mouth-watering snack you can’t pass up.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://colemannatural.com/wp-content/uploads/2023/08/Three-Cincinnati-chili-dogs-on-a-wood-table-920.jpg"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Kansas City Hot Dog",
        description = "Many believe that Kauffman Stadium put Kansas City dogs on the map—turning the conventional American hot dog into more of a Rueben extravaganza. Just like the traditional Rueben sandwich, this dog displays all of those key ingredients, such as tangy Swiss cheese, sauerkraut, caraway seeds, and that velvety-smooth Thousand Island dressing. Sometimes you’ll even spot a pickle sandwiched in between the buns. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://colemannatural.com/wp-content/uploads/2023/08/Three-Kansas-city-hot-dogs-on-a-wood-cutting-board-920.jpg"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Sonoran Hot Dog",
        description = "It’s first assembled by stuffing a smoky, bacon-wrapped grilled dog in a bolillo-style bun, a Mexican bread that is ultra soft inside, with a crunchy exterior. Sometimes you’ll even get a layer of pinto beans spread in the bun for added flavor and texture. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://colemannatural.com/wp-content/uploads/2023/08/Three-Sonoran-hot-dogs-on-a-cutting-board-next-to-a-knife-920.jpg"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Los Angeles Hot Dog",
        description = "Many natives also layer on generous amounts of ketchup, mayonnaise, and mustard, along with giant poblano pepper. The L.A. Dog represents the best of California street food and certainly adds to the city’s eclectic culture.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://colemannatural.com/wp-content/uploads/2023/08/Close-up-of-a-Los-Angeles-hot-dog-toppings-920.jpg"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Puka Hot Dog",
        description = "The Puka Dog concept involves piercing a long bread roll with a skewer to nestle the steamed dog inside. You can opt for a blanket of melted American cheese or make it more flavorful by adding various condiments inside the hollowed-out bun, including ketchup, mustard, tropical fruit relishes like passion fruit, mango, or coconut, and more! So if you find yourself in Hawaii, don’t get a tan on the beach without this snack by your side.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://www.thespruceeats.com/thmb/6GUcR9vorsT2ntIKDq34oEjuyUM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/puka-dog-4774786-hero-01-190ed36488114e7bb2bab9ec3684c454.jpg"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Half-smoke",
        description = "A half-smoke is a type of hot dog found in Washington, D.C., and the surrounding region. Larger, spicier, and with more coarsely-ground meat than a regular hot dog, the sausage is often half-pork and half-beef, smoked, and served with herbs, onion, and chili sauce.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://www.seriouseats.com/thmb/qQxeIzHn6wHsN5Usa04Aeg42ZlY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__images__2014__10__20140930-dchalfsmokes-meatsandfoods-brian-oh-17e81e4830014a458bc391686e082c5f.jpg",
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Seattle Hot Dog",
        description = "A Seattle-style hot dog, locally referred to as a Seattle Dog, is a hot dog served in a bun slathered with cream cheese. In Seattle, the dogs are sold from food carts, especially outside stadiums on game day and as a late-night meal outside the city's music venues.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQPJf9GgTDb1fp0Xvqr3jenepljv79i09kippTTuO9mKJLUMbL3L92jIQAaiO1P_gUs5i3mYPCkaOKCNQiza_ij-5RkhGPx37xvqNrSXg8ktQ"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "",
        description = "A slaw dog is a hot dog topped with coleslaw, a Southern American favorite that often also includes chili, mustard, and onions. While the exact ingredients can vary by region, this type of hot dog typically features a grilled hot dog in a bun, layered with a generous portion of creamy or tangy, vinegar-based coleslaw.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://lifewiththecrustcutoff.com/wp-content/uploads/2019/05/Slaw-Dogs-4.jpg",
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Texas Tommy",
        description = "The Texas Tommy is an American hot dog dish from Philadelphia and the Philadelphia metro area, consisting of a hot dog prepared with bacon and cheese. Despite the name, it was invented in the 1950s in Pottstown, Pennsylvania, a town right outside Philadelphia.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyNd2fUaOLrFSt8Gx4SV_dzE8kckVJbL1lxCGXdR9Jfvw_7ukp44hRt89Pyg4vXBvXwaQSjGtEwE5F76XV4UWUuOUzV4SbYUViZeFfW5OE"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Italian Hot Dog",
        description = "An Italian hot dog is a type of hot dog popular in New Jersey, United States, made by Jimmy Buff and his wife Mary Racioppi. His family continues the restaurant Jimmy Buff's to this day. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRIkJ6YSsWqDp6unsvw_EbjpO0sWIqV-NFXvWHdauEKItsUYLohO8R0cSz0bPXIJ8348qeVSWwayaIRR_ijRdbRg8_38rXtQRtqHrk4iLtv"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Polish Boy",
        description = "The Polish Boy is a sausage sandwich native to Cleveland, Ohio. It consists of a link of kielbasa sausage placed in a bun, and covered with a layer of french fries, a layer of barbecue sauce and a layer of coleslaw.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT1t8qw2fsb0ewGUFPsm1yvYqH2aoQve6T7t1Qcq4FQxKN5_qoZqB4s8F8AqHar0q1Yg9_9e6ke0V_XKnXz0XOuXTaiOENDESlzjUt7HTl6"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Chili Hot Dog",
        description = "A chili dog is a hot dog served in a bun and topped with a meat sauce, typically chili con carne. Additional toppings may include cheese, onions, and mustard.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRyPJQqEUmTy2aXkmOeiINKZkC1myQlVcoWjM1OilZi8xqJz83omM8QmMyugX8T5gtI-OrR_2sdTbZTXuRDhiJRlticpHr7T_WBru-fDXPh"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Cheese Hot Dog",
        description = "A cheese dog is a hot dog served with cheese or processed cheese on it, or stuffed within it as a filling.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT1zzcb1by-42gjKKrUyZqmSFQmrySEBtDMbsd0gxggcrv-0WVjsjHMePaZLMjsXdMO-g230H2HChFKB2am6zhkprQdpInusieppd6mTWFO"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Atlanta Hot Dog",
        description = "An Atlanta hot dog can refer to the \"Varsity Dog,\" a signature item from The Varsity restaurant, featuring a chili-topped hot dog with a secret chili, alongside a variety of traditional toppings like mustard, ketchup, onions, and relish, often served with a side of their hand-cut fries. It can also refer to variations like a \"Scrambled Dog,\" which is a chopped hot dog covered in chili, onions, dill pickle slices, and oyster crackers, or other hot dogs with ingredients like Vidalia onions, peaches, and coleslaw.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9iur8BKAScH2LLO8K2AHsFemtaMS4euYhcw&s"
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Bobby's Beer Brats",
        description = "For his Milwaukee-style brats, Bobby braises the sausages in beer, then moves them to the grill to achieve a golden-brown crust.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://www.keyingredient.com/uploads/media/29/17/5f2d3cfd438f73017a198fa03e5e20a3b08e.jpg?1560436497",
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Chipotle Chili Cheese Dogs",
        description = "Foot-long hot dogs get a Southwestern kick from chili powder, cumin and chipotle hot sauce.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://hips.hearstapps.com/hmg-prod/images/chili-dog-recipe-2-68237b9b3e6e9.jpeg?crop=0.502xw:1.00xh;0.250xw,0&resize=1200:*",
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Pretzel Buns With Grilled Dogs",
        description = "Sandwich King Jeff Mauro makes his own easy pretzel buns to fill with grilled dogs and a spicy cheese sauce.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://stpierrebakery-com.s3.amazonaws.com/app/uploads/2023/09/Pretzel-Family-Style-Brioche-Hot-Dogs-1440x960.jpg",
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Malai Chicken Hot Dog",
        description = "Get excited for summer heat with these spicy South Asian-inspired \"hot dogs,\" made with ground chicken and lots of fresh herbs and chiles. For a cool finish, top them off with an easy mango mustard spiked with mint.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://www.licious.in/blog/wp-content/uploads/2021/04/3-600x600.jpg",
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Wisconsin Beef & Cheddar Brats",
        description = "Sandra grills beef-and-cheddar brats on the grill and then tops them with onions cooked with beer.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9GSDNB0nq0ReLFlhHs4eAB46SNMbmMqmFbQ&s",
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Pescabrat",
        description = "Justin uses a mix of scallops and skinless salmon or cod to make these tasty seafood dogs. You don't need to bother with casings — he simply wraps them tightly with plastic wrap and cooks them in boiling water. After they've cooled, unwrap the pescabrats and finish them off on the grill.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://i.pinimg.com/564x/50/08/1a/50081a4ecf4b0fe35b92378941ee2e39.jpg",
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Miso Hot Dog",
        description = "A quick miso-mayo and a topping of crunchy radishes, nori and fresh herbs turn your boring cookout hot dogs into an elevated, gourmet bite.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://images.ctfassets.net/0yf82hjfqumz/2HRiLDxT2VQwKapPW9eN2N/0eb26f69c56d76f573370f5b744696f0/Korealainen_miso_hodari_vaaka_netti.jpg",
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Brooklyn's Corniest Hot Dogs",
        description = "This New York City-inspired dog is topped with caramelized onions, bacon, corn and cheese.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNr_E1m_Zqktvj9XjTipOo9PFoMedDGYyY8w&s",
    ),
    FoodItem(
        categoryID = "HotDog",
        title = "Nacho Hot Dog",
        description = "Dress up your dog with chunky guacamole and Bobby's Grilled Tomato-Chipotle Salsa.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = hotdogFoodAddOns,
        image = "https://www.simplymaderecipes.com/wp-content/uploads/2018/03/Mexican-Hot-Dog-main.png",
    ),
)