package com.example.comida.dummy.foodItems

import com.example.comida.dummy.foodAddOns.pastaFoodAddOns
import com.example.comida.models.FoodItem
import kotlin.random.Random


val pastaCategory = listOf<FoodItem>(
    FoodItem(
        categoryID = "Pasta",
        title = "Spaghetti",
        description = "Long, thin, and cylindrical spaghetti is probably the most popular and recognizable pasta worldwide. Its shape is ideal for smooth sauces, making it the go-to choice for Pesto Spaghetti, Easy Spaghetti Bolognese, and the family favorite: spaghetti and meatballs. Puck Creamy Tomato Sauce is a delicious go-to for spaghetti dinner in a snap. Our article on spaghetti will show you how easy it is to prepare spaghetti and bring everyone together for a fun and delicious Pasta Night.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://cdn.puckarabia.com/4a5010/globalassets/pasta/pasta-recipes/pesto-spaghetti-.jpeg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Capellini",
        description = "Capellini’s thin and delicate strands inspired the delightful nickname \"angel hair.\" It is quick and easy to cook in about 3–5 minutes, making it a favorite choice for busy moms. Capellini’s light and tender texture is suitable for light sauces made with ingredients you may already have on hand, such as olive oil, garlic, and canned or fresh tomatoes. Toss this versatile pasta with zesty Puck Creamy Tomato Sauce or use it to showcase seafood dishes such as capellini with clam sauce. Its delicate nature allows it to complement subtle flavors without overshadowing the other ingredients, making it a family-friendly choice that everyone can enjoy together.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://www.thespruceeats.com/thmb/9y4iehTGvAD_V31UIdmI2NdTTtM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/angel-hair-pasta-with-tomatoes-3054078-hero-01-b40c65a9de2846298b67a9091d43a29f.jpg",
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Pici",
        description = "Pici looks like fat spaghetti – it is a thick, hand-rolled pasta from Tuscany with a slightly irregular shape. While traditionally served with simple, rustic sauces such as aglione (garlic sauce), it can also be used in a robust ragù sauce because of the way it soaks up hearty flavors. Another easy pici option is tossing it with our delicious Puck Mushroom Sauce with Pepper, a hearty go-to for fast family meals any day of the week. Like other pastas, pici’s fast and easy preparation frees you up to focus on family time.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://legallyhealthyblonde.com/wp-content/uploads/2022/11/picicacio-featured.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Tortellini",
        description = "Tortellini are small ring-shaped pastas filled with a mixture of meats and/or cheeses. They come from the Emilia region in Italy and are often served in broth or with a light cream sauce to highlight their delicate texture and savory filling. Tortellini dishes are beloved during festive seasons and family gatherings. With so many different recipes available — whether it’s Tortellini with Mushrooms, Ricotta, or Beef, or simply tortellini topped with our smooth, creamy Puck Four Cheese Sauce — you’re sure to find family-pleasing options that can be prepared and served in minutes.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://cdn.puckarabia.com/4aae5d/globalassets/pasta/pasta-recipes/tortellini-with-cheese-sauce.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Ravioli",
        description = "Ravioli are square or round pockets of pasta that encase a variety of fillings, from traditional ricotta and spinach to beef to pumpkin or butternut squash. They are usually coated with a sauce that mirrors the filling's flavors, such as butter and sage or a simple tomato sauce. Try simple Homemade Ravioli with a Cream Cheese Filling, or for a fun twist that the kids will love, fry the ravioli until crispy and serve it with a side of delicious Puck Creamy Tomato Sauce. You can also keep it simple with just a little butter, a sprinkling of grated cheese, and whatever herbs you have on hand. It’s your home, so however you choose to make it, you make it special!",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://cdn.puckarabia.com/4a4e14/globalassets/pasta/pasta-recipes/homemade-ravioli.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Agnolotti",
        description = "Agnolotti are similar to ravioli but are typically rectangular or crescent-shaped. They are traditionally filled with roasted meats and vegetables to showcase the flavors of the Piedmont region's rich culinary traditions. Unlike ravioli, the edges of agnolotti are folded together. They are often served with a meat sauce or a butter and sage sauce, which complements the richness of the filling. But you don’t need to stick to tradition — make it your own! Whether you’re adding Puck Creamy Tomato Sauce or trying a new twist on a beloved classic, it’s all about creating delicious moments that your family will love.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://cookingmydreams.com/wp-content/uploads/2025/01/Agnolotti-del-Plin-3.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Rigatoni",
        description = "Rigatoni is a large, ridged, tube-shaped pasta with a slight curve. Due to its wide shape, it is perfect for capturing chunky ingredients and thicker meat- or vegetable-based sauces. Rigatoni becomes firm and chewy when cooked, which makes it excellent for baked pasta dishes. For a mouth-watering classic that will nourish and satisfy your loved ones, simply bake your rigatoni with our creamy Four Cheese Sauce. Add-ins like nutmeg make it special with little effort on your part.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://cdn.puckarabia.com/48f811/globalassets/pasta/pasta-recipes/creamy-broccoli-pasta.jpg"
    ),
    FoodItem(
        id = "",
        categoryID = "Pasta",
        title = "Cannelloni",
        description = "Cannelloni is a popular pasta type, known for its large and cylindrical shape that is perfect for stuffing and baking. Its large tube shape can hold many types of fillings the whole family will love, such as ricotta, a combination of cheeses, or meat. You can create warm family moments with delicious dishes like beef or chicken cannelloni with Mushroom. Or simply top cannelloni with Puck Béchamel Sauce with Cheese or our Creamy Tomato Sauce for a satisfying family favorite that you can easily prepare any day of the week, leaving you more time for the people who matter most.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://cdn.puckarabia.com/4a4cee/globalassets/pasta/pasta-recipes/chicken-cannelloni-with-mushroom-.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Bucatini",
        description = "With its long, cylindrical shape, bucatini looks similar to spaghetti, but is notably thicker and has a hollow center. This structure allows bucatini to absorb sauces and gives it its distinctive texture. This pasta type is especially favored for dishes that use smooth, tomato-based sauces such as creamy Puck Creamy Tomato Sauce, as it allows the sauce to easily seep into its hollow core. Its unique texture will spark your loved ones’ interest and inspire you to create your family’s next favorite pasta dish.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://www.allrecipes.com/thmb/6l5hB2_lEuyvGO70vX6yLF4pkCU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/274411-BucatiniCacioePepe-ddmfs-3x4-8224-97ca529992254e578bdb742c85aba0f5.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Paccheri",
        description = "Paccheri are large, thick, tube-shaped pasta, like rigatoni but bigger. Their smooth texture and wide, hollow centers make them ideal for filling. Popular fillings for paccheri are ricotta cheese and sausage. This pasta maintains its firm texture when cooked, allowing the sauce to fill it up nicely. Feel free to experiment with whatever fillings and sauces you desire — we recommend Puck Creamy Tomato Sauce — then just pop it in the oven and get ready to share a memorable family meal that everyone will love.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://www.theslowroasteditalian.com/wp-content/uploads/2022/07/Paccheri-Pasta-SQUARE.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Penne",
        description = "Penne, a type of short pasta, is incredibly versatile. You can use it in a variety of ways, from gratins to pasta salads to a simple dish of penne, sauce, and cheese. Its hollow centers are perfect for sauces and other ingredients, ensuring that every bite is packed with flavor. Penne is available with smooth or ridged surfaces. This popular and versatile pasta is a great choice for everything from baked dishes to tomato, cream, and pesto sauces. For a simple, classic dish that’s sure to be a hit, try topping penne with our Puck Creamy Tomato Sauce and a bit of Puck Shredded Creamy Mozzarella Cheese. Make it your way, with the secret ingredients your family will always love, because you make it special!",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://cdn.puckarabia.com/4a5096/globalassets/pasta/pasta-recipes/cheesy-pasta-in-foil.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Ziti",
        description = "Ziti, sometimes known as \"zite,\" is a tube-shaped pasta that is medium in width and slightly narrower and shorter than its big brother, the rigatoni. It has smooth sides and straight-cut ends, with a firm texture that holds up beautifully in baked pasta dishes. Ziti is commonly paired with marinara sauce, cheese, and occasionally meat. Or, for a fuss-free meal in no time, try ziti with Puck Creamy Tomato Sauce. (Hint: You can also use Puck Béchamel Sauce with Cheese or Puck Cooking Cream to add a cozy layer of creamy smoothness to baked ziti dishes.) Like all pasta, ziti is easily customizable, so feel free to add your own special touch according to your loved ones’ preferences.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://sugarspunrun.com/wp-content/uploads/2025/01/Baked-Ziti-Recipe-1-of-1-2-500x500.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Cavatappi",
        description = "Cavatappi, also known as corkscrew pasta, is characterized by its short, spiral-shaped tubes. The ridges and spiral shape make it ideal for holding creamy and thick sauces. It’s also just plain fun for children to eat! Sometimes referred to as \"double elbow,” cavatappi is used similarly to elbow pasta, including the macaroni dishes your family loves. For a carefree family meal in minutes, simply toss some cavatappi with Puck Four Cheese Sauce — sure to bring smiles all around the table.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://amindfullmom.com/wp-content/uploads/2025/03/Recipe-with-Cavatappi-Pasta.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Tagliatelle",
        description = "Tagliatelle is a long, flat pasta that looks like a ribbon. It is made with eggs and has a rich, tender texture when cooked. While it is often confused with fettuccine, tagliatelle is slightly wider. Its broad surface area makes it perfect for holding and absorbing thicker sauces. Traditionally, it is used with ragù or bolognese, but it also pairs well with creamy sauces, like in our Mushroom Tagliatelle recipe. For a fast, family-pleasing meal, combine either our Puck Mushroom Sauce with Peppers or Puck Cooking Cream with chopped fresh herbs and mushrooms, if you have them. It’s perfect for those busy days when you want to spend more time enjoying a comforting meal with your loved ones.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://cdn.puckarabia.com/49a7e0/globalassets/cooking-cream/embedded-640x480_0000_tagliatelle-with-creamy-mushroom-sauce.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Fettuccine",
        description = "Fettuccine is another very popular type of pasta. It is similar to tagliatelle but narrower. Made with eggs, this pasta has a rich texture that is tender yet firm when cooked. Fettuccine is a classic in Italian cuisine and has become popular in many kitchens around the world. It is famously used in dishes such as fettuccine Alfredo or Chicken Fettuccine Alfredo. It also pairs well with seafood. Create a flavorful Alfredo with Puck Béchamel Sauce with Cheese or Puck Cooking Cream, along with Parmesan cheese. Or bring joy to the table with this creamy Shrimp Fettuccine Alfredo recipe, which is sure to become a family favorite. Fettuccine is perfect for those evenings when you want to create special mealtime moments that everyone will cherish.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://cdn.puckarabia.com/4a4ed0/globalassets/pasta/pasta-recipes/chicken-fettuccine-alfredo.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Linguine",
        description = "Linguine is a classic pasta type perfectly suited for recipes with lighter sauces. It is long and flat, thinner than fettuccine yet thicker than spaghetti. Its shape makes it ideal for clinging to small ingredients, ensuring an even sauce coating. While linguine is the pasta of choice for seafood dishes, it also works well with simple olive oil-based sauces like pesto, or tomato-based sauces like Puck’s zesty Tomato Sauce. Think of linguini as an ally for moms who want to serve up great flavors and create warm family memories effortlessly.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://cdn.puckarabia.com/48f8ba/globalassets/pasta/pasta-recipes/white-sauce-linguine-with-zucchini.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Pappardelle",
        description = "Pappardelle is a large, wide, flat pasta that pairs beautifully with thick meat sauces or combinations featuring mushrooms and truffles. Its name derives from \"pappare,\" an Italian verb meaning “to gobble up” — playfully hinting at the fun, messy way it is enjoyed — especially by kids! When cooked, pappardelle becomes chewy; its broad shape effortlessly captures anything you can imagine, from chunky ingredients and dense sauces to convenient go-tos like Puck Mushroom Sauce with Peppers. So gather the family, embrace the mess, and create delicious memories around the dinner table.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://winniesbalance.com/wp-content/uploads/2022/06/Balsamic-beef-pappardelle-pasta-basil-portabello-simple-quick.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Lasagna",
        description = "Lasagna sheets are famously used for lasagna. The large, flat sheets make perfect layers to hold various meat, vegetable, and cheese sauces. Popular family favorites include Easy Beef Lasagna with Béchamel Sauce and Spinach and Ricotta Lasagna. Let your imagination guide you on a culinary journey that will delight your loved ones at the table. You can find lasagna sheets in both dried and fresh forms. Fresh lasagna sheets can also be used for cannelloni, where they are rolled around flavorful fillings and baked in the oven – often covered in a delicious sauce, as we do in this family-pleasing recipe for Chicken Cannelloni with Mushroom. Our creamy Puck Béchamel Sauce with Cheese or Puck Creamy Tomato Sauce make irresistible lasagna recipes quick to prepare, giving you more time for the people you love.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://cdn.puckarabia.com/48f82e/globalassets/pasta/pasta-recipes/easy-beef-lasagna-with-bchamel-sauce.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Short pasta",
        description = "Short pasta comes in all kinds of fun, exciting, and interesting shapes with curves and ridges that are perfect for catching sauces. It’s a hit with kids, who love the playful shape, and it’s ideal for dishes like casseroles and pasta salads or paired with chunky sauces for extra flavor and visual appeal. Some well-known types include orzo and fusilli, but there are also less common ones like trofie and radiatori. We are here to help you discover and enjoy all kinds of short pasta so you can tailor your meals and include new recipes to your list of Mom’s specialties.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://mypureplants.com/wp-content/uploads/2023/06/casarecce-pasta-14.jpg"
    ),
    FoodItem(
        categoryID = "",
        title = "Orzo",
        description = "Orzo, also known as pastina or \"little pasta,\" is a small, rice-shaped pasta known for its tender texture. Due to its simplicity and versatility, orzo is similar to rice in many ways, making it a popular choice for soups and salads. Its compact size allows it to absorb flavors beautifully, allowing you to pair it effortlessly with light sauces and broths. For something a little heartier, try this Tomato Vegetable Soup, which is made with Puck Creamy Tomato Sauce, and enrich it with orzo. No matter how you use it, think of versatile, customizable, and quick-cooking orzo when it’s time for a comforting dish the whole family can enjoy.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://agrillforallseasons.com/wp-content/uploads/2023/01/tomato-orzo-1-2.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Fusilli",
        description = "Fusilli is a short, spiral-shaped pasta available in various lengths and thicknesses. It is extremely popular and used in many different family-friendly recipes. Its corkscrew-like shape is excellent at capturing sauces, making it a favorite for tomato-based sauces, such as our delicious Puck Creamy Tomato Sauce, paired with meat or vegetables. Or toss it with some Puck Cooking Cream for a one-pot meal that gives you more time to cherish dinner with loved ones. Like many other short pasta varieties, fusilli also works well in pasta salads and dishes with pesto. Keep some on hand for a go-to family pleaser that you can easily customize to suit any occasion or taste.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://cdn.puckarabia.com/48f93d/globalassets/pasta/pasta-recipes/salmon-and-broccoli-pasta.jpg"
    ),
    FoodItem(
        categoryID = "",
        title = "Orecchiette",
        description = "Orecchiette, meaning \"little ears\" in Italian, is a small, concave pasta that looks slightly disk-shaped. Its signature shape has a few gaps and indentations that are great for capturing sauces and smaller ingredients. Because of this feature, orecchiette is a popular choice for rich and robust sauces. It is often served with meat and vegetable ragù, but there are endless ways to make it your own. Does your family love creamy cheese-based dishes? Puck Cooking Cream is a great option for orecchiette. These delightful bite-sized bits let you create dishes that will bring joy to your family and loved ones — because you make it special.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://images.immediate.co.uk/production/volatile/sites/30/2022/02/Orecchiette-with-butter-beans-0872a01.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Farfalle",
        description = "Farfalle is a small pasta shaped like bow ties or butterflies and looks as if it has been pinched in the middle. Its shape is not just a visual gimmick: it provides different textures in each bite. While the center is firm, the thinner outer areas become more tender when cooked. Farfalle is also a very adaptable pasta type; make it special with the flavors your family loves in pasta salads and recipes with vegetables and creamy sauces like our hearty Puck Four Cheese Sauce. Children especially enjoy its playful shape, making farfalle an excellent choice for a memorable family gathering.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSKVEy1yeJ6E5-xkfClYOnGzpOfgSQBv1-mA&s"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Strozzapreti",
        description = "Strozzapreti are elongated, twisted pasta shapes about five centimeters in length. They also have a ridged surface that makes them great for gripping creamy sauces or pesto. The name \"strozzapreti\" translates to \"priest-choker\" in Italian. According to legend, priests loved this pasta so much that they would eat it quickly — and might choke because it was so delicious. The truth of this tale might be uncertain, but the delightful taste of strozzapreti is undeniable. Make it shine your own way, with flavorful toppings like Puck Mushroom Sauce with Pepper or our creamy Puck Four Cheese Sauce, to delight the ones you love the most.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://italianfoodforever.com/wp-content/uploads/2015/09/strozzapretti14.jpg"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Radiatori",
        description = "Their name almost gives it away. Radiatori are small pasta shapes with ridges that make it look like old-fashioned radiators. They are often used in soups and chunky meat and vegetable sauces, and like all short pastas, work beautifully in baked dishes. The reason is simple: their shape, texture, ridges, and gaps trap the sauce perfectly. Try it in Pasta Bake with White Sauce, a creamy favorite made with Puck Béchamel Sauce with Cheese. When you’re short on time, radiatori is your go-to pasta for creating a quick, delicious, nourishing meal that your family will cherish.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrBqSo3B6mS9p_n6FnLfDiYnrD7O0S0_uD-g&s"
    ),
    FoodItem(
        categoryID = "Pasta",
        title = "Conchiglie",
        description = "While conchiglie is the most popular name for this type of pasta, it is also known as shells because of its resemblance to conch shells. It comes in various shapes and sizes and is famed for its partly hollow center, which acts like a nest for your choice of sauces and fillings. This versatile pasta can be used in everything from baked dishes and soups to meat and vegetable sauces. Or put a delightful twist on mac and cheese night with conchiglie and our Puck Four Cheese Sauce. Any way you personalize it, conchiglie gives you plenty of options for family-pleasing dishes for any occasion.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pastaFoodAddOns,
        image = "https://veryveganish.com/wp-content/uploads/2022/09/Featured-Conchiglie-Rosa-with-Vegan-Rose-Pink-Pasta-Sauce-1.jpg"
    ),
)