package com.example.comida.dummy.foodItems

import com.example.comida.dummy.foodAddOns.pizzaFoodAddOns
import com.example.comida.models.FoodItem
import kotlin.random.Random


val pizzaCategory = listOf<FoodItem>(
    FoodItem(
        categoryID = "Pizza",
        title = "Detroit-Style",
        description = "The owners pressed pizza dough into a deep, rectangular steel pan from a local auto shop, loaded it with cheese and sauce (in that order), and baked it until crisp. The result was something unexpectedly delicious and unique. The crust was light, crisp, and oily, and the cheese burnished around the rim of the pie. Although Buddy’s still uses the same steel pans, seasoned from years of use, Detroit-style pizza has become so popular that similar pans are now readily available to recreate the hefty, square pizza at home. Using a dark metal pan is the key to getting the correct bake on the pizza and containing all the cheese. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_730,h_548/k%2FPhoto%2FRecipe%20Ramp%20Up%2F2022-02-Detroit-Pizza%2Fdetroit-pizza_272d38-horizontal-crop"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "New York-Style",
        description = "New York takes its pizza pretty seriously, and in New York City, it’s hard to walk more than two blocks without seeing a slice shop. Despite claims that the local water is the secret to great New York-style pizza, there is more to the style. Italian immigrants brought their history and recipes for Neapolitan pizza to New York in the late 1800s, but the style adapted to fit their new circumstances, including cooking the pies in a coal-fired oven and making the pizzas larger with a slightly thicker and more evenly risen crust. Lombardi’s was the first (or one of the first) pizzerias to offer New York-style pizza in 1905 in lower Manhattan, in a neighborhood we now call Little Italy. The large pies are rolled or tossed in the air until moderately thin and then topped first with sauce and then cheese and other toppings. When baked, it’s crispy and chewy with enough structure that you can pick up the large slice and fold it in half like a local to eat without it drooping dramatically or having the toppings slide off. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_730,h_548/k%2FPhoto%2FSeries%2F2023-09-how-to-reheat-pizza-in-an-airfryer%2Fhow-to-reheat-pizza-in-an-air-fryer-087_0eb64f-horizontal-crop"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Neapolitan-Style",
        description = "Neapolitan-style pizza is easy to pick out in a lineup. The dinner plate-size pies have a very thin center and an impressive puffed rim, which is well browned from the one- to two-minute bake time in a wood-fired brick oven. The style comes from the Campania region of Italy, which includes Naples, the birthplace. Traditionally, the yeasted dough rises at room temperature all day before being carefully stretched and shaped to retain all the air pockets built up during proofing. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_730,h_445/stock%2FGettyImages-1393599671"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Sicilian",
        description = "In a world of round pizzas, the thick square of Sicilian at the end of the counter in the pizza shop stands out. Originally hailing from Sicily, a true Sicilian, called sfincione, is markedly different than what we see now as Sicilian pizza. Sfincione, which means “sponge,” is named for the thick, airy crust it resembles. Sfincione features a tomato-based sauce cooked with onions, anchovies, and herbs, a topping of goat or sheep’s milk cheese, and a sprinkle of breadcrumbs. As Sicilian pizza adapted to American ingredients and tastes, the thickness and shape of the crust stayed the same, but the toppings morphed to include a more simply seasoned tomato sauce and mozzarella cheese. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_730,h_487/stock%2Fshutterstock_2339059493"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Chicago Deep-Dish",
        description = "Is it a casserole? Is it a pie? Chicago deep-dish pizza is a unique, hefty, fork-and-knife meal like no other (it’s certainly not pizza you can pick up by the slice). Similar to other pizza styles, deep-dish pizza was created by Italian immigrants in America. But unlike New York-style or New Haven-style, deep-dish was a way to enjoy pizza in a totally new way, rather than riffing off the classic styles. Pizzeria Uno was the birthplace of deep-dish pizza in 1943 in Chicago, and it was quickly a hit, prompting other shops to open and create their take on this new type of pizza. While some liken Chicago deep-dish to Detroit-style (both baked in deep metal pans with a decadent slightly fried crust), deep-dish pizza differs in the construction and the crust. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_730,h_487/k%2Farchive%2F544fc5a57c28eca6edc766f6b7dcba0d74bc5c38"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "New Haven-Style",
        description = "t is not a typo — it is apizza. New Haven, Connecticut, is an improbable spot for a pizza mecca, but it has become one. In the early 1900s, a large number of Italians from the Naples area settled in New Haven, and with their Italian dialect and accent, apizza was born, based on how they said the word pizza. The three most well-known pizzerias are Frank Pepe Pizzeria Napoletana, Modern Apizza, and Sally’s Apizza. All three cook their pizzas in hot brick ovens. Pepe’s and Sally’s are fueled by coal, but Modern, although it originally was coke-fueled (a coal byproduct), now uses an open flame. While they create pizzas of the same style, each shop does things slightly differently. Patrons have their preferences between the three shops, and these allegiances are a heated topic of debate.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_730,h_537/stock%2Fshutterstock_1972459070"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Grandma",
        description = "Grandma pizza is another pizza baked in a large pan, but there are a few details that make it different from other styles. The origins of Grandma pizza can be traced to Long Island home kitchens and came about as a solution to a problem. The problem was that Italian immigrants had little time and little home ovens but still wanted to produce a quality pizza. By letting the dough rise on a baking sheet for a relatively short amount of time before stretching, topping, and baking, you end up with a pizza with a crust that is thinner and crispier than on a Sicilian pizza — and ready in a fraction of the time. A generous amount of oil on the baking sheet keeps the dough from sticking, browns the bottom, and adds richness. Not all pizza shops carry Grandma-style, but it is becoming more readily available.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_730,h_487/k%2FPhoto%2FRecipes%2F2023-12-grandma-pizza%2Fgrandma-pizza-539-horizontal"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Roman-Style",
        description = "There are two popular Roman-style pizzas. Pizza al taglio translates to “pizza by the cut,” as you can walk into a shop, point at the kind of pizza you want, and they will cut you a square or rectangular piece with scissors and weigh it to determine the cost. It is baked in huge rectangular pans that can be as big as 3 to 4 feet long and features a thin, crisp crust, sturdy enough so people can eat it while walking around. Pizza tonda, also called Scrocchiarella, has a more classic look. Tonda, which means round or circular in Italian, shares a similarly thin and crispy crust to pizza al taglio but is rolled into an individually sized round pizza. The crackly thin crust is baked until charred in spots and has a light texture. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_730,h_487/stock%2Fshutterstock_2268354647"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "California-Style",
        description = "California-style pizza is one of the more nebulous types on this list because it’s not defined by a certain crust, topping, or construction. The style was born in the 1980s with chefs like Ed LaDou at Spago and Alice Waters at Chez Panisse who were cooking with local California ingredients and integrating them into classic dishes, like pizza. This was also the beginning of California Pizza Kitchen, which opened in 1985 with LaDou, who was responsible for developing the initial menu and their now-signature pizza, The Original BBQ Chicken Pizza.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_730,h_487/stock%2Fshutterstock_1963398058"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "St. Louis-Style",
        description = "St. Louis-style pizza spurs a lot of strong opinions. From the unique, thin, unleavened crust to the gooey cheese called Provel that goes on top, it’s a style unlike any other. Ino’s is the original spot in St. Louis credited for creating St. Louis-style pizza. The round pizza is cut vertically and then horizontally into squares, which are sturdier in holding all the heavy toppings than a long, wide triangle. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_730,h_487/stock%2Fshutterstock_1538728469"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Quad City-Style",
        description = "The Quad Cities are a cluster of cities on the border of Southeastern Iowa and Northwestern Illinois that are home to a unique style of pizza. According to the tourist website for Quad Cities, what makes Quad Cities-style pizza unique is a combination of the cut of the pie, the assembly, and the crust ingredients, plus the fact that it’s usually cut with long scissors versus a knife or pizza wheel. Although a few different pizza shops claim the creation of the style, they all opened around the same time in the 1950s. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_730,h_548/k%2FEdit%2Fquad-city-pizza"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Pizza al Taglio",
        description = "Pizza al Taglio–translating to pizza by the slice–is a beloved Italian street food. As we mentioned above, it tends to be cooked in large trays to be sold by weight, making it a popular, convenient meal in major Italian cities from its birthplace in Rome and beyond. Slices are often cut to order, which means you can choose both the size and the toppings. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://cdn.shopify.com/s/files/1/0299/7764/1097/files/Mushroom_and_ricotta_calzone.webp?v=1748513084"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Calzone",
        description = "This folded type of pizza, often baked or fried, creates a portable, handheld version of the classic dish. The dough is folded over a variety of fillings, sealing in the ingredients and forming a distinguishable half-moon shape. Traditional fillings for a calzone include ricotta, mozzarella, and a mix of cured meats such as ham or salami, along with vegetables like mushrooms, spinach, and peppers. These ingredients offer a rich, flavorful combination that contrasts with the simpler toppings of a traditional pizza.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjbxGShIdQ9yS8jf1t4Gz-3bBO9HRH10HMQw&s"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Margherita Pizza",
        description = "Pizza Margherita, also known as Margherita pizza, is, together with the pizza marinara, the typical Neapolitan pizza. It is roundish in shape with a raised edge and seasoned with hand-crushed peeled tomatoes, mozzarella, fresh basil leaves, and extra virgin olive oil.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvxr03tbV7YpcBmjrgYQCpBvupjDaiZSvvN1sXiMFu0hnVT8Brk61_p3cKRjhMfUUCAiocGhZkXJuCd9ud5-ixSSm7rKcbbbFvfZNWYEhe"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Pan pizza",
        description = "Pan pizza is a pizza baked in a deep dish pan or sheet pan. Turin-style pizza, Italian tomato pie, Sicilian pizza, Greek pizza, Chicago-style pizza, and Detroit-style pizza may be considered forms of pan pizza. Pan pizza also refers to the thick style popularized by Pizza Hut in the 1960s.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLiL6UD6D_EKn_4FmZMBePns1SUV_okK6kyyFEJ8HFliXI5GMH_1OgcJJ13teEOZFBAzxxE13ZyUfT9J2C7C9M9EQzn7puuIq1SlQk9Vs"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Hawaiian pizza",
        description = "Hawaiian pizza is a pizza invented in Canada, topped with pineapple, tomato sauce, mozzarella cheese, and either ham or bacon.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT8cJTMjJEckKnGLH3DB46TTzJ58deM6SyVKFrDNW3ryvJqX9dpgcJWbMV7UTHVTYsYcPr1ex-8acb7a2apmTUpgwxBhC91UtnlG-cWuyDg"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Meat Pizza",
        description = "If pepperoni just isn’t enough, and you’re looking for a pie with a bit more heft, a meat-lover’s pizza is a perfect and popular choice. Pile on ground beef and sausage for a hearty meal.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSysXsZvSgT1y82a771RXmF1xQNQ2_puE9mBg&s",
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Veggie Pizza",
        description = "When you want to jazz up your cheese pizza with color and texture, veggies are the perfect topping. And you’re only limited by your imagination. Everything from peppers and mushrooms to eggplant and onions makes for a flavorful veggie pizza variety.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://aplantifulpath.com/wp-content/uploads/2024/07/vegan-vegetable-pizza-square.jpg",
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "BBQ Chicken Pizza",
        description = "If you love BBQ chicken, and you love pizza, why not put them together? This unique pizza flavor has long been a cult favorite of sports fans and college kids. The chicken slathered over the top of a pie gives it a tangy, sweet flavor that can’t be beaten.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://bakingamoment.com/wp-content/uploads/2024/06/IMG_3443-barbecue-chicken-pizza.jpg",
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Buffalo Pizza",
        description = "Who says your pizza has to be strictly tomato-sauce based? Branch out with some buffalo sauce on your pie. All its spicy, salty, buttery goodness is a natural pairing for pizza.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://www.allrecipes.com/thmb/GK6zZbKChUTMmq9vHhGMbyPbQGA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/BuffaloChickenPizza_AR_Feb-Mar-24x3-07e2fcb74a1d472499f4c22980825b13.jpg",
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Pepperoni Pizza",
        description = "There’s a reason this is one of the most popular pizzas in the U.S. Who doesn’t love biting into a crispy, salty round of pepperoni?",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://ik.imagekit.io/smithfield/armour/4353bced-f940-00d0-8c6e-13a0a4a7f5c2/2ac60829-5178-4a6e-80cf-6ca43d862cee/Quick-and-Easy-Pepperoni-Pizza-700x700.jpeg?tr=w-1160,c-at_max,f-auto",
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Supreme Pizza",
        description = "When you can’t decide which toppings to get, it’s time for the supreme pizza. The “supreme” refers to the litany of toppings that come scattered on these pies, from sausage to vegetables to pepperoni. And it’s the combination of flavors that really makes it sing.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGsO8_BXeu1PTx2mLrb7OPazuxz4hJp273FQ&s"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Boardwalk pizza",
        description = "\"Boardwalk pizza\" can refer to the distinctive style of thin-crust, rectangular pie with a sweet sauce and mozzarella cheese that is a staple of the New Jersey shore, or it can refer to a specific restaurant chain and brand name called \"Boardwalk Pizza\" that operates in various locations, such as the one in Ellisville, MO, which features hand-tossed pizzas and other menu items. ",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJqBd-DvFiTEWX-hkoS8i3Gdo7bkZzdp1K0w&s"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Miami Pizza",
        description = "Bienvenido a Miami! With a large slice of its population being from Cuba, it is no wonder that Miami developed its own style of pizza- Cuban pizza. The dough is thick, as it is left to rise longer than usual. The toppings are actually pressed into the dough and held together by a generous layer of whole milk low- moisture mozzarella and gouda cheeses. The toppings range from your usual ham and pepperoni to picadillo beef and even plantains.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://dishcrawl.com/wp-content/uploads/2021/05/miami-cuban-pizza.jpg"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Milano Pizza",
        description = "Maybe the least known among typical Italian pizza styles, the Milan-style pizza is a “newer” version created in the 1950s. It is thick and fluffy, like focaccia, even though it only needs to rise for one hour. The toppings include peeled crushed tomatoes and a mountain of mozzarella cheese, sliced into thin strips that must cover the WHOLE surface of the pizza. This is then topped with oregano and sardines.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://dishcrawl.com/wp-content/uploads/2021/05/milan-style.jpg"
    ),
    FoodItem(
        categoryID = "Pizza",
        title = "Mexico Pizza",
        description = "True Mexican pizza is called “tlayuda” and is made with giant flour tortillas topped with lard, mashed beans, fresh queso, chile sauce and sometimes meats and avocado. A dream come true if you  love both tacos and pizza! The recipe is from Oaxaca and the tortillas are made by hand and griddled on large stones. Not surprisingly, it is one of Mexico’s best street foods.",
        price = Random.nextDouble(1.0, 50.0),
        ratingValue = Random.nextDouble(1.0, 5.0),
        discountPercentage = Random.nextDouble(1.0, 25.0),
        weight = Random.nextDouble(1.0, 2.5),
        isFavorites = Random.nextBoolean(),
        isFreeDelivery = Random.nextBoolean(),
        deliveryTime = Random.nextDouble(1.0, 60.0),
        deliveryFees = Random.nextDouble(1.0, 30.0),
        addOns = pizzaFoodAddOns,
        image = "https://dishcrawl.com/wp-content/uploads/2021/05/mexican-tlayuda-pizza.jpg"
    ),
)