package com.example.comida.dummy.specialOffers

import com.example.comida.models.SpecialOffer
import com.example.comida.ui.theme.OnboardingBackgroundColor2
import com.example.comida.ui.theme.PrimaryButtonColor
import kotlin.random.Random


val availableSpecialOffers = listOf<SpecialOffer>(
    SpecialOffer(
        title = "Rodeo King",
        restaurantName = "Burger King",
        ratingValue = Random.nextDouble(1.0, 5.0),
        isFreeDelivery = Random.nextBoolean(),
        price = Random.nextDouble(1.0, 50.0),
        offerImage = "https://i.ytimg.com/vi/THnssqKARC4/maxresdefault.jpg",
        backgroundColor = PrimaryButtonColor,
        description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a vulputate diam. Morbi vel lorem non nisi egestas iaculis eu at quam. Aliquam ullamcorper, nulla eu vulputate congue, felis felis blandit ligula, ut posuere erat justo et nibh. In suscipit lorem tincidunt, ultricies ante et, iaculis neque. Donec tortor erat, porta imperdiet ultrices vitae, rutrum quis nunc. Donec ipsum neque, condimentum sed feugiat fermentum, cursus id est. Aenean fermentum tortor et nisi convallis, et efficitur nunc faucibus. In dictum sapien quis vestibulum auctor. Proin et dapibus sem. Vivamus et ex non purus accumsan ornare ultricies ut lacus.",
        deliveryTime = Random.nextDouble(1.0, 60.0),
    ),
    SpecialOffer(
        title = "Philly Cheese",
        restaurantName = "McDonald’s",
        ratingValue = Random.nextDouble(1.0, 5.0),
        isFreeDelivery = Random.nextBoolean(),
        price = Random.nextDouble(1.0, 50.0),
        offerImage = "https://www.lep.co.uk/jpim-static/image/2025/03/19/14/06/philly-cheese-stack.jpeg?width=1200&enable=upscale",
        backgroundColor = OnboardingBackgroundColor2,
        description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a vulputate diam. Morbi vel lorem non nisi egestas iaculis eu at quam. Aliquam ullamcorper, nulla eu vulputate congue, felis felis blandit ligula, ut posuere erat justo et nibh. In suscipit lorem tincidunt, ultricies ante et, iaculis neque. Donec tortor erat, porta imperdiet ultrices vitae, rutrum quis nunc. Donec ipsum neque, condimentum sed feugiat fermentum, cursus id est. Aenean fermentum tortor et nisi convallis, et efficitur nunc faucibus. In dictum sapien quis vestibulum auctor. Proin et dapibus sem. Vivamus et ex non purus accumsan ornare ultricies ut lacus.",
        deliveryTime = Random.nextDouble(1.0, 60.0),
    ),
    SpecialOffer(
        title = "Santa Monica",
        restaurantName = "Bestia",
        ratingValue = Random.nextDouble(1.0, 5.0),
        isFreeDelivery = Random.nextBoolean(),
        price = Random.nextDouble(1.0, 50.0),
        offerImage = "https://smdp.com/wp-content/uploads/sites/21/2024/07/resturant_img02_852x480px-1.jpg",
        backgroundColor = PrimaryButtonColor,
        description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a vulputate diam. Morbi vel lorem non nisi egestas iaculis eu at quam. Aliquam ullamcorper, nulla eu vulputate congue, felis felis blandit ligula, ut posuere erat justo et nibh. In suscipit lorem tincidunt, ultricies ante et, iaculis neque. Donec tortor erat, porta imperdiet ultrices vitae, rutrum quis nunc. Donec ipsum neque, condimentum sed feugiat fermentum, cursus id est. Aenean fermentum tortor et nisi convallis, et efficitur nunc faucibus. In dictum sapien quis vestibulum auctor. Proin et dapibus sem. Vivamus et ex non purus accumsan ornare ultricies ut lacus.",
        deliveryTime = Random.nextDouble(1.0, 60.0),
    ),
    SpecialOffer(
        title = "Vegi Pasta",
        restaurantName = "Osteria Mozza",
        ratingValue = Random.nextDouble(1.0, 5.0),
        isFreeDelivery = Random.nextBoolean(),
        price = Random.nextDouble(1.0, 50.0),
        offerImage = "https://www.theworlds50best.com/discovery/filestore/jpg/OsteriaMozza-LosAngeles-USA-01.jpg",
        backgroundColor = OnboardingBackgroundColor2,
        description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a vulputate diam. Morbi vel lorem non nisi egestas iaculis eu at quam. Aliquam ullamcorper, nulla eu vulputate congue, felis felis blandit ligula, ut posuere erat justo et nibh. In suscipit lorem tincidunt, ultricies ante et, iaculis neque. Donec tortor erat, porta imperdiet ultrices vitae, rutrum quis nunc. Donec ipsum neque, condimentum sed feugiat fermentum, cursus id est. Aenean fermentum tortor et nisi convallis, et efficitur nunc faucibus. In dictum sapien quis vestibulum auctor. Proin et dapibus sem. Vivamus et ex non purus accumsan ornare ultricies ut lacus.",
        deliveryTime = Random.nextDouble(1.0, 60.0),
    ),
    SpecialOffer(
        title = "Domino's Classic",
        restaurantName = "Domino's",
        ratingValue = Random.nextDouble(1.0, 5.0),
        isFreeDelivery = Random.nextBoolean(),
        price = Random.nextDouble(1.0, 50.0),
        offerImage = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9dcxQ9HpKAQprX5aazCtFWROv92o55_pW5w&s",
        backgroundColor = PrimaryButtonColor,
        description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a vulputate diam. Morbi vel lorem non nisi egestas iaculis eu at quam. Aliquam ullamcorper, nulla eu vulputate congue, felis felis blandit ligula, ut posuere erat justo et nibh. In suscipit lorem tincidunt, ultricies ante et, iaculis neque. Donec tortor erat, porta imperdiet ultrices vitae, rutrum quis nunc. Donec ipsum neque, condimentum sed feugiat fermentum, cursus id est. Aenean fermentum tortor et nisi convallis, et efficitur nunc faucibus. In dictum sapien quis vestibulum auctor. Proin et dapibus sem. Vivamus et ex non purus accumsan ornare ultricies ut lacus.",
        deliveryTime = Random.nextDouble(1.0, 60.0),
    ),
    SpecialOffer(
        title = "Supreme",
        restaurantName = "Pizza Hut",
        ratingValue = Random.nextDouble(1.0, 5.0),
        isFreeDelivery = Random.nextBoolean(),
        price = Random.nextDouble(1.0, 50.0),
        offerImage = "https://www.tastingtable.com/img/gallery/10-popular-menu-items-from-pizza-hut-ranked/2-medium-thin-n-crispy-pizza-hawaiian-chicken-1727183059.jpg",
        backgroundColor = OnboardingBackgroundColor2,
        description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a vulputate diam. Morbi vel lorem non nisi egestas iaculis eu at quam. Aliquam ullamcorper, nulla eu vulputate congue, felis felis blandit ligula, ut posuere erat justo et nibh. In suscipit lorem tincidunt, ultricies ante et, iaculis neque. Donec tortor erat, porta imperdiet ultrices vitae, rutrum quis nunc. Donec ipsum neque, condimentum sed feugiat fermentum, cursus id est. Aenean fermentum tortor et nisi convallis, et efficitur nunc faucibus. In dictum sapien quis vestibulum auctor. Proin et dapibus sem. Vivamus et ex non purus accumsan ornare ultricies ut lacus.",
        deliveryTime = Random.nextDouble(1.0, 60.0),
    ),
    SpecialOffer(
        title = "Rutt's Hut Rippers",
        restaurantName = "Rutt's Hut",
        ratingValue = Random.nextDouble(1.0, 5.0),
        isFreeDelivery = Random.nextBoolean(),
        price = Random.nextDouble(1.0, 50.0),
        offerImage = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3gbq0ib5wmQosQTHsxuwMU_RZE0dAnwHvXw&s",
        backgroundColor = PrimaryButtonColor,
        description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a vulputate diam. Morbi vel lorem non nisi egestas iaculis eu at quam. Aliquam ullamcorper, nulla eu vulputate congue, felis felis blandit ligula, ut posuere erat justo et nibh. In suscipit lorem tincidunt, ultricies ante et, iaculis neque. Donec tortor erat, porta imperdiet ultrices vitae, rutrum quis nunc. Donec ipsum neque, condimentum sed feugiat fermentum, cursus id est. Aenean fermentum tortor et nisi convallis, et efficitur nunc faucibus. In dictum sapien quis vestibulum auctor. Proin et dapibus sem. Vivamus et ex non purus accumsan ornare ultricies ut lacus.",
        deliveryTime = Random.nextDouble(1.0, 60.0),
    ),
    SpecialOffer(
        title = "The Leo",
        restaurantName = "Portillo's (Illinois)",
        ratingValue = Random.nextDouble(1.0, 5.0),
        isFreeDelivery = Random.nextBoolean(),
        price = Random.nextDouble(1.0, 50.0),
        offerImage = "https://www.mystateline.com/wp-content/uploads/sites/17/2025/05/porillos-the-leo.jpg?w=1280",
        backgroundColor = OnboardingBackgroundColor2,
        description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a vulputate diam. Morbi vel lorem non nisi egestas iaculis eu at quam. Aliquam ullamcorper, nulla eu vulputate congue, felis felis blandit ligula, ut posuere erat justo et nibh. In suscipit lorem tincidunt, ultricies ante et, iaculis neque. Donec tortor erat, porta imperdiet ultrices vitae, rutrum quis nunc. Donec ipsum neque, condimentum sed feugiat fermentum, cursus id est. Aenean fermentum tortor et nisi convallis, et efficitur nunc faucibus. In dictum sapien quis vestibulum auctor. Proin et dapibus sem. Vivamus et ex non purus accumsan ornare ultricies ut lacus.",
        deliveryTime = Random.nextDouble(1.0, 60.0),
    ),
    SpecialOffer(
        title = "Dunkin Oreo",
        restaurantName = "Dunkin",
        ratingValue = Random.nextDouble(1.0, 5.0),
        isFreeDelivery = Random.nextBoolean(),
        price = Random.nextDouble(1.0, 50.0),
        offerImage = "https://tofuu.getjusto.com/orioneat-local/resized2/h9SSEqMcehZw9THZR-2400-x.webp",
        backgroundColor = PrimaryButtonColor,
        description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a vulputate diam. Morbi vel lorem non nisi egestas iaculis eu at quam. Aliquam ullamcorper, nulla eu vulputate congue, felis felis blandit ligula, ut posuere erat justo et nibh. In suscipit lorem tincidunt, ultricies ante et, iaculis neque. Donec tortor erat, porta imperdiet ultrices vitae, rutrum quis nunc. Donec ipsum neque, condimentum sed feugiat fermentum, cursus id est. Aenean fermentum tortor et nisi convallis, et efficitur nunc faucibus. In dictum sapien quis vestibulum auctor. Proin et dapibus sem. Vivamus et ex non purus accumsan ornare ultricies ut lacus.",
        deliveryTime = Random.nextDouble(1.0, 60.0),
    ),
    SpecialOffer(
        title = "Ice Cream Donuts",
        restaurantName = "Baskin Robbins",
        ratingValue = Random.nextDouble(1.0, 5.0),
        isFreeDelivery = Random.nextBoolean(),
        price = Random.nextDouble(1.0, 50.0),
        offerImage = "https://s3.amazonaws.com/static.realcaliforniamilk.com/media/new-recipes/donut_ice_cream_sandwich.jpg",
        backgroundColor = OnboardingBackgroundColor2,
        description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a vulputate diam. Morbi vel lorem non nisi egestas iaculis eu at quam. Aliquam ullamcorper, nulla eu vulputate congue, felis felis blandit ligula, ut posuere erat justo et nibh. In suscipit lorem tincidunt, ultricies ante et, iaculis neque. Donec tortor erat, porta imperdiet ultrices vitae, rutrum quis nunc. Donec ipsum neque, condimentum sed feugiat fermentum, cursus id est. Aenean fermentum tortor et nisi convallis, et efficitur nunc faucibus. In dictum sapien quis vestibulum auctor. Proin et dapibus sem. Vivamus et ex non purus accumsan ornare ultricies ut lacus.",
        deliveryTime = Random.nextDouble(1.0, 60.0),
    ),
    SpecialOffer(
        title = "Michelin-Starred",
        restaurantName = "Rezdôra",
        ratingValue = Random.nextDouble(1.0, 5.0),
        isFreeDelivery = Random.nextBoolean(),
        price = Random.nextDouble(1.0, 50.0),
        offerImage = "https://images.squarespace-cdn.com/content/v1/607d95468ee6257ceab9d30a/9ee0b686-1010-4fe1-ac33-65b25287760f/Gramigna+giallo+e+verde.jpg",
        backgroundColor = PrimaryButtonColor,
        description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a vulputate diam. Morbi vel lorem non nisi egestas iaculis eu at quam. Aliquam ullamcorper, nulla eu vulputate congue, felis felis blandit ligula, ut posuere erat justo et nibh. In suscipit lorem tincidunt, ultricies ante et, iaculis neque. Donec tortor erat, porta imperdiet ultrices vitae, rutrum quis nunc. Donec ipsum neque, condimentum sed feugiat fermentum, cursus id est. Aenean fermentum tortor et nisi convallis, et efficitur nunc faucibus. In dictum sapien quis vestibulum auctor. Proin et dapibus sem. Vivamus et ex non purus accumsan ornare ultricies ut lacus.",
        deliveryTime = Random.nextDouble(1.0, 60.0),
    ),
    SpecialOffer(
        title = "Napoletana Pizza",
        restaurantName = "Tony's Pizza Napoletana",
        ratingValue = Random.nextDouble(1.0, 5.0),
        isFreeDelivery = Random.nextBoolean(),
        price = Random.nextDouble(1.0, 50.0),
        offerImage = "https://goldbelly.imgix.net/uploads/merchant/main_image/1175/tonys-pizza-napoletano.1ccd4529618a20560e046d34b23a4e42.jpg?ixlib=react-9.10.0&ar=1%3A0.5625&fit=crop&w=3840&auto=format",
        backgroundColor = OnboardingBackgroundColor2,
        description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a vulputate diam. Morbi vel lorem non nisi egestas iaculis eu at quam. Aliquam ullamcorper, nulla eu vulputate congue, felis felis blandit ligula, ut posuere erat justo et nibh. In suscipit lorem tincidunt, ultricies ante et, iaculis neque. Donec tortor erat, porta imperdiet ultrices vitae, rutrum quis nunc. Donec ipsum neque, condimentum sed feugiat fermentum, cursus id est. Aenean fermentum tortor et nisi convallis, et efficitur nunc faucibus. In dictum sapien quis vestibulum auctor. Proin et dapibus sem. Vivamus et ex non purus accumsan ornare ultricies ut lacus.",
        deliveryTime = Random.nextDouble(1.0, 60.0),
    ),
)